name: Publish to GCR

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build
        run: docker build .
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_SA_KEY }}
          project_id: ${{ secrets.GCR_PROJECT }}
          export_default_credentials: true
      - name: Authenticate Docker
        run: |-
          gcloud auth configure-docker
      - name: Build
        run: docker build . -t "gcr.io/${{ secrets.GCR_PROJECT }}/${{ secrets.GCR_SERVICE }}:$GITHUB_SHA"
      - name: Push to Google Container Registry
        run: docker push "gcr.io/${{ secrets.GCR_PROJECT }}/${{ secrets.GCR_SERVICE }}:$GITHUB_SHA"
      # Deploy image to Cloud Run
      - name: Deploy GCR
        run: |-
          gcloud run deploy "${{ secrets.GCR_SERVICE }}" \
            --quiet \
            --region "${{ secrets.GCR_REGION }}" \
            --image "gcr.io/${{ secrets.GCR_PROJECT }}/${{ secrets.GCR_SERVICE }}:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated
